# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_vsveipdr_Gs_booster <- function(t_max, y, alpha, beta, gamma_d, gamma_r, thetas, M, dG1s, dG2s, dG3s, mu_1, mu_2, mu_3, kappa, rho, omega, r_beta) {
    .Call(`_objectfunctionsbooster_sim_vsveipdr_Gs_booster`, t_max, y, alpha, beta, gamma_d, gamma_r, thetas, M, dG1s, dG2s, dG3s, mu_1, mu_2, mu_3, kappa, rho, omega, r_beta)
}

object_kappa_tra_booster <- function(x, dat_sim, t_V, iter, thetas, M, mu_1, mu_2, mu_3, r_beta, bspline2) {
    .Call(`_objectfunctionsbooster_object_kappa_tra_booster`, x, dat_sim, t_V, iter, thetas, M, mu_1, mu_2, mu_3, r_beta, bspline2)
}

object_kappa_booster <- function(x, dat_sim, t_V, iter, thetas, M, mu_1, mu_2, mu_3, r_beta, bspline2, inter_b_min, inter_b_max, inter_l) {
    .Call(`_objectfunctionsbooster_object_kappa_booster`, x, dat_sim, t_V, iter, thetas, M, mu_1, mu_2, mu_3, r_beta, bspline2, inter_b_min, inter_b_max, inter_l)
}

sim_vsveipdr_Gs_booster_reinfect <- function(t_max, y, alpha, beta, gamma_d, gamma_r, thetas, M, dG1s, dG2s, dG3s, mu_1, mu_2, mu_3, mu_r, kappa, rho, omega, r_beta) {
    .Call(`_objectfunctionsbooster_sim_vsveipdr_Gs_booster_reinfect`, t_max, y, alpha, beta, gamma_d, gamma_r, thetas, M, dG1s, dG2s, dG3s, mu_1, mu_2, mu_3, mu_r, kappa, rho, omega, r_beta)
}

object_kappa_tra_booster_reinfect <- function(x, dat_sim, t_V, iter, thetas, M, mu_1, mu_2, mu_3, mu_r, r_beta, bspline2) {
    .Call(`_objectfunctionsbooster_object_kappa_tra_booster_reinfect`, x, dat_sim, t_V, iter, thetas, M, mu_1, mu_2, mu_3, mu_r, r_beta, bspline2)
}

object_kappa_booster_reinfect <- function(x, dat_sim, t_V, iter, thetas, M, mu_1, mu_2, mu_3, mu_r, r_beta, bspline2, inter_b_min, inter_b_max, inter_l) {
    .Call(`_objectfunctionsbooster_object_kappa_booster_reinfect`, x, dat_sim, t_V, iter, thetas, M, mu_1, mu_2, mu_3, mu_r, r_beta, bspline2, inter_b_min, inter_b_max, inter_l)
}

