# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_vsveipdr <- function(t_max, y, alpha, beta, gamma_d, gamma_r, theta, M, phi_1, phi_2, mu_1, mu_2, kappa, rho, r_beta) {
    .Call(`_objfunction_sim_vsveipdr`, t_max, y, alpha, beta, gamma_d, gamma_r, theta, M, phi_1, phi_2, mu_1, mu_2, kappa, rho, r_beta)
}

object_alpha <- function(x, dat_sim_before, t_choose, iter, theta, M, r_beta, bspline1) {
    .Call(`_objfunction_object_alpha`, x, dat_sim_before, t_choose, iter, theta, M, r_beta, bspline1)
}

sim_vsveipdr_Gs <- function(t_max, y, alpha, beta, gamma_d, gamma_r, theta, M, dG1s, dG2s, mu_1, mu_2, kappa, rho, r_beta) {
    .Call(`_objfunction_sim_vsveipdr_Gs`, t_max, y, alpha, beta, gamma_d, gamma_r, theta, M, dG1s, dG2s, mu_1, mu_2, kappa, rho, r_beta)
}

object_kappa_tra <- function(x, dat_sim, t_V, iter, theta, M, mu_1, mu_2, r_beta, bspline2) {
    .Call(`_objfunction_object_kappa_tra`, x, dat_sim, t_V, iter, theta, M, mu_1, mu_2, r_beta, bspline2)
}

object_kappa <- function(x, dat_sim, t_V, iter, theta, M, mu_1, mu_2, r_beta, bspline2, inter_b_min, inter_b_max, inter_l) {
    .Call(`_objfunction_object_kappa`, x, dat_sim, t_V, iter, theta, M, mu_1, mu_2, r_beta, bspline2, inter_b_min, inter_b_max, inter_l)
}

